# Generated by Django 6.0.3 on 2026-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='liable_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
