# Generated by Django 6.0.3 on 2026-03-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_liable_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='recommendation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
